#!/bin/bash

if ! docker image list  | grep docker_git > /dev/null 2>&1; then
    docker build \
        --build-arg "USER_UID=$(id -u)" \
        --build-arg "USER_GID=$(id -g)" \
        --build-arg "USER_NAME=$(id -un)" \
        --tag docker_git \
        "$(dirname "$0")"
fi

docker run -it --rm \
    -v "$HOME:$HOME" \
    -w "$PWD" \
    --rm \
    -u "$(id -u)" \
   docker_git \
   "$@"
